image: registry.gitlab.com/caspermeijn/docker-images/fedora-build-onvifviewer:latest
before_script:
    - cd ..
    - git clone https://github.com/KDAB/KDSoap.git
    - mkdir build-KDSoap
    - cd build-KDSoap/
    - cmake ../KDSoap/ -DCMAKE_INSTALL_PREFIX=/usr/local
    - make
    - make install
    - cd ..
    - mkdir build-kdsoap-ws-discovery-client
    - cd build-kdsoap-ws-discovery-client
    
fedora:
    stage: build
    script: 
        - cmake $CI_PROJECT_DIR 
        - make 
        - make install
        - ctest --verbose
        
pages:
    script:
    - cmake $CI_PROJECT_DIR
    - make docs
    - mv docs/html/ $CI_PROJECT_DIR/public/
    artifacts:
        paths:
        - public
    only:
    - master

