# Copyright (C) 2019-2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0
   
fedora:
    stage: build
    image: registry.gitlab.com/caspermeijn/docker-images/fedora-build-onvifviewer:latest
    before_script:
        - cd ..
        - git clone https://github.com/KDAB/KDSoap.git
        - mkdir build-KDSoap
        - cd build-KDSoap/
        - cmake ../KDSoap/ -DCMAKE_INSTALL_PREFIX=/usr/local
        - make
        - make install
        - cd ..
        - mkdir build-kdsoap-ws-discovery-client
        - cd build-kdsoap-ws-discovery-client
    script: 
        - cmake $CI_PROJECT_DIR 
        - make 
        - make install
        - ctest --verbose
        
fedora-clang:
    stage: build
    image: registry.gitlab.com/caspermeijn/docker-images/fedora-build-onvifviewer:latest
    variables:
        CC: clang
        CXX: clang++
    before_script:
        - microdnf -y install ninja-build clang clang-tools-extra clazy
        - git clone https://github.com/KDAB/KDSoap.git
        - mkdir build-KDSoap
        - cd build-KDSoap/
        - cmake ../KDSoap/ -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local
        - ninja
        - ninja install
        - cd ..
        - mkdir build-kdsoap-ws-discovery-client
        - cd build-kdsoap-ws-discovery-client
    script: 
        - cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. 
        - ninja 
        - clang-tidy -p build-kdsoap-ws-discovery-client/compile_commands.json **/*.cpp
        - clazy-standalone -p build-kdsoap-ws-discovery-client/compile_commands.json -checks=level0,level1,level2 **/*.cpp
    artifacts:
        paths:
        - build-kdsoap-ws-discovery-client/
        
#clazy:
    #stage: test
    #image: fedora:31
    #dependencies:
        #- fedora-clang
    #before_script:
        #- dnf -y install clazy
    #script:
        #- clazy-standalone -p build-kdsoap-ws-discovery-client/compile_commands.json **/*.cpp
        
#clang-tidy:
    #stage: test
    #image: fedora:31
    #dependencies:
        #- fedora-clang
    #before_script:
        #- dnf -y install clang-tools-extra
    #script:
        #- clang-tidy -p build-kdsoap-ws-discovery-client/compile_commands.json **/*.cpp
        
pages:
    image: registry.gitlab.com/caspermeijn/docker-images/fedora-build-onvifviewer:latest
    before_script:
        - cd ..
        - git clone https://github.com/KDAB/KDSoap.git
        - mkdir build-KDSoap
        - cd build-KDSoap/
        - cmake ../KDSoap/ -DCMAKE_INSTALL_PREFIX=/usr/local
        - make
        - make install
        - cd ..
        - mkdir build-kdsoap-ws-discovery-client
        - cd build-kdsoap-ws-discovery-client
    script:
        - cmake $CI_PROJECT_DIR
        - make docs
        - mv docs/html/ $CI_PROJECT_DIR/public/
    artifacts:
        paths:
        - public
    only:
    - master

reuse:
  stage: test
  image: fsfe/reuse:latest
  script:
    - reuse lint || echo "Always report as successful. For now this is a informational test"
