ubuntu-1804:
    image: ubuntu:18.04
    stage: build
    script: 
        - apt install extra-cmake-modules
        - cd .. && git checkout https://github.com/caspermeijn/KDSoap.git
        - cd ../KDSoap &&  mkdir build && cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && make && make install
        - cd ../kdsoap-ws-discovery-client && mkdir build && cd build
        - cmake .. && make && make install
